# Generated by Django 4.0.2 on 2022-02-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='tempo_duracao',
            field=models.DateField(),
        ),
    ]
